from __future__ import annotations

from .engine import create_initial_state
from .events import build_fallback_events, validate_events
from .expression_clients import (
    DEFAULT_OPENAI_MODEL,
    DEFAULT_TIMEOUT_SECONDS,
    HTTPTransport,
    LLMClient,
    LLMProviderError,
    MAX_OPENAI_API_KEY_LENGTH,
    MAX_OPENAI_BASE_URL_LENGTH,
    MAX_OPENAI_MODEL_LENGTH,
    MAX_OPENAI_PROMPT_LENGTH,
    MAX_OPENAI_RESPONSE_BYTES,
    MAX_OPENAI_RESPONSE_TEXT_LENGTH,
    MAX_TIMEOUT_SECONDS,
    OPENAI_RESPONSES_URL,
    OpenAICompatibleChatClient,
    OpenAIResponsesClient,
    _chat_completions_url,
    _default_transport,
    _extract_chat_completion_text,
    _extract_response_text,
    _has_control_character,
    _is_control_character,
    _json_request_headers,
    _models_url,
    _normalize_api_key,
    _normalize_base_url,
    _normalize_model,
    _normalize_timeout,
    _parse_timeout,
    _validated_response_text,
    client_config_from_env,
    client_config_from_settings,
    fetch_provider_model_ids,
)
from .expression_expressor import (
    ShinsekaiAIExpressor,
    ThreadPoolExecutor,
    TimeoutError,
    _ensure_expression_request,
    _fallback_events_for_invalid_snapshot,
    _format_tool_result,
    _invalid_snapshot_prompt,
    _is_fallback_events,
    _json_candidate_from_llm_text,
    _state_from_snapshot,
    _validated_llm_response_text,
    build_default_ai_expressor,
    build_expression_prompt_preview,
)
from .expression_parser import (
    ExpressionPayloadError,
    _dialogue_parser_fallback_reason,
    _is_allowed_legacy_expression_event,
    _is_safe_legacy_sprite,
    _normalize_speech_schema_event,
    normalize_expression_event,
    parse_shinsekai_object_stream,
    stringify_event,
)
from .expression_request import (
    MAX_ACTION_LABEL_LENGTH,
    MAX_CHARACTER_NAME_LENGTH,
    MAX_DELTA_TEXT_LENGTH,
    MAX_FEEDBACK_LENGTH,
    MAX_GOAL_LENGTH,
    MAX_LONG_TERM_MEMORY_CATEGORY_LENGTH,
    MAX_LONG_TERM_MEMORY_SOURCE_LENGTH,
    MAX_MEMORY_KIND_LENGTH,
    MAX_MEMORY_MOTION_LENGTH,
    MAX_MEMORY_SUMMARY_LENGTH,
    MAX_MODE_LENGTH,
    MAX_MOTION_LENGTH,
    MAX_PERCEPTION_SUMMARY_LENGTH,
    MAX_RECENT_MEMORY,
    MAX_TOOL_RESULTS,
    MAX_TOOL_TIMESTAMP_LENGTH,
    ExpressionRequest,
    _as_dict_list,
    _expression_payload_from_context,
    _expression_payload_from_snapshot,
    _finite_float,
    _replace_control_characters,
    _sanitize_actions,
    _sanitize_long_term_memory,
    _sanitize_recent_memory,
    _sanitize_tool_results,
    _short_string,
    ensure_expression_request,
)
from .expression_settings import ExpressionSettings
from .snapshot import CompanionSnapshot

_ExpressionPayloadError = ExpressionPayloadError
_normalize_expression_event = normalize_expression_event
_parse_shinsekai_object_stream = parse_shinsekai_object_stream
_stringify_event = stringify_event
